### ISSUE TITLE
Greeting Functionality

### ISSUE THREAD

**Issue by RafaelDavisH** [chingu-voyages/v13-toucans-team-03#10]

**Comment by zaynaib** [comment]
@RafaelDavisH I am done with the basic greeting functionality. I made two pull request.

**Comment by RafaelDavisH** [comment]
@Zaynaib awesome!!

**Comment by RafaelDavisH** [comment]
@zaynaib I tested the app locally and I got an error with the `greetTypes.json` 404 (Not Found). All I had to do was remove `/v13-toucans-team-03`. So it worked with the path of `"/js/greeting/greetTypes.json"`. Can you test it again locally on your end please @ming-yong , @sophi-li to see if it works on your local machines.
