### ISSUE TITLE
Google folder purge

### ISSUE THREAD

**Issue by myg-main** [chingu-voyages/v13-toucans-team-03#36]
I suggest we:
- (Keep it)Deleting unused google document "Backlog".
- (Did it)Adding "Toucans workflow" to keep all the things that we agree on.
- (Did it)Change "Team Norms, OS Contribution, Code of Conduct" to "OS draft" and remove the team norms section(similar info is in "Toucans workflow").
- (Did it)Decide a time for master branch migration and PR review.

**Comment by zaynaib** [comment]
@ming-yong @RafaelDavisH @sophi-li I thought that we agreed on Tuesday and Friday nights for master branch migration and PR review. But I guess we don't have the time written. Maybe each one of us pick a day/time that works for us and we can all practice doing a pull review.

**Comment by myg-main** [comment]
@zaynaib I agree! I had added that information on the "Toucans workflow" google doc where time is left empty.

In addition to that, I suggest we decide on a time to review PRs that need teammates to review.

**Comment by zaynaib** [comment]
@ming-yong I agree with the 3rd bullet point. I want to keep the Backlog document so it can be an archive of the progress of what our team has done so far. It's still active. We just didn't use it this week. 🤷‍♀

**Comment by myg-main** [comment]
@zaynaib Ohh I see, it's not being updated for a while and we seems to have our progress documented on the blog posts so I thought we are not using it anymore... Sorry for that 🙏 We will keep it then.

**Comment by sophi-li** [comment]
@ming-yong I changed "Team Norms, OS Contribution, Code of Conduct" to "OS Guide [DRAFT]". I also removed the text content w/ team norms since it's already on the Toucans workflow doc. Thanks for these suggestion on consolidating our docs!
