### ISSUE TITLE
Move feature branches and PR Steps to a different file.

### ISSUE THREAD

**Issue by RafaelDavisH** [chingu-voyages/v13-toucans-team-03#4]
- README would be information for users where they will find a Table of Content with links to other files. As an example:

- Wireframes
- Feature Branches and PR Steps

**Comment by sophi-li** [comment]
@RafaelDavisH Should I move the setup list that you currently have on the readme into it's own md file and link it in the table of contents(ToC)? Thanks!

I have a draft of the ToC here: https://docs.google.com/document/d/1xpAza4OsnnIzLg1OnWiV39mdtx7f04Pp_W2ipIWJ11k/edit

**Comment by sophi-li** [comment]
@RafaelDavisH @ming-yong @zaynaib Hi all, is there anything you want to add to the table of contents for the readme file?

Draft here: https://docs.google.com/document/d/1xpAza4OsnnIzLg1OnWiV39mdtx7f04Pp_W2ipIWJ11k/edit
 Feel free to add directly to the doc. 

I'll send a PR on Monday morning. We can always keep updating as our app develops. Thanks!

**Comment by RafaelDavisH** [comment]
> @RafaelDavisH Should I move the setup list that you currently have on the readme into it's own md file and link it in the table of contents(ToC)? Thanks!
> 
> I have a draft of the ToC here: https://docs.google.com/document/d/1xpAza4OsnnIzLg1OnWiV39mdtx7f04Pp_W2ipIWJ11k/edit

Yes, that would be a great update for the README doc. I was going to update the README steps,
but if you do the move can you add these updated steps, please?
```
### Setup Locally

1. Clone the GH repo locally
    - `git clone https://github.com/chingu-voyages/v13-toucans-team-03.git`.
2. Move into the repo folder 
    - ` cd v13-toucans-teams-03.git`.
3. Pull the latest changes and merge to the local branch.
    - `git pull origin development`.
4. Create a feature branch.
    - `git branch feat/my-awesome-feature`.
5. Move to the feature branch.
    - `git checkout feat/my-awesome-feature`.
6. Stage changes.
    ALL changes
    - `git add .`

    Specific changes to a file
    - `git add <file name>`
7. Commit locally and write an exceptionally well-written commit message.
    `git commit -m 'short description of changes'`.
8. Push feature branch changes.
    `git push origin feat/my-awesome-feature`.

### Making a Pull Request.
9. On GitHub create a PR to promote changes to the `development` branch.
10. Follow the PR Template checklist.
10. Assign @zaynaib to review the pull-request.
11. A few days after the PR has been approved and promoted remove the feature branch.
```

**Comment by sophi-li** [comment]
@RafaelDavisH Yes, I can update! Do you want it in the README or in its own MD file (while I'll link in the ToC)?

**Comment by RafaelDavisH** [comment]
> @RafaelDavisH Yes, I can update! Do you want it in the README or in its own MD file (while I'll link in the ToC)?

The local and PR steps on to a separate file. Also, it would be great to add the logo on the
README doc. I'll make a suggestion issue for this.

**Comment by myg-main** [comment]
> @RafaelDavisH @ming-yong @zaynaib Hi all, is there anything you want to add to the table of contents for the readme file?

@sophi-li Nothing at the moment.

**Comment by zaynaib** [comment]
@sophi-li Is it possible to add a information about how to run the app on a local machine?
Also add a link to the deployed MoTo app in the readme doc.
