### ISSUE TITLE
Adding the MoTo Logo the README doc.

### ISSUE THREAD

**Issue by RafaelDavisH** [chingu-voyages/v13-toucans-team-03#40]
As @sophi-li is updating the README doc and changing it to have an about description, and a table of content for the MoTo application, I believe it would be proper to add the MoTo logo somewhere as well.

@zaynaib , @ming-yong @sophi-li What you think about this suggestion?

**Comment by sophi-li** [comment]
@RafaelDavisH It'd be great to add the MoTo logo on the ToC on the README. Maybe at the top where we describe what it is?

If yall want to add it, @RafaelDavisH lmk where I can find the logo and I can add it!

**Comment by RafaelDavisH** [comment]
@sophi-li You can download the logo from Discord or better yet, I just uploaded to our google drive folder.

**Comment by myg-main** [comment]
@RafaelDavisH Love the idea!

**Comment by zaynaib** [comment]
@RafaelDavisH  @ming-yong  @sophi-li We should add links to our home github files in the readME doc next to our names.
